Repository Ilopgut/3.2-EJERCICIO_CALCULADORA-DESCUENTO-CON-OPERACIONES-ARITM-TICAS-, pull requests merged in 2024-11, with the labels that each got.

#3 Commit a revisar promociones
  index.php
Labels: enhancement

#14 Commit uso de operadores lógicos a revisar
  index.php
Labels: enhancement

#16 Calculo de precio por unidad
  index.php
Labels: enhancement

#18 Commit revisar comentario
  index.php
Labels: documentation

#19 Calculadora v2.0
  index.php
Labels: version
